### ISSUE TITLE
Pretrained models for inference

### ISSUE THREAD

**Issue by amil-rp-work** [lucasxlu/TransFBP#1]
Hey @lucasxlu ,

Thanks a lot for providing amazing results on the benchmark datasets. I was wondering on how to inference the TransFBP results on custom images. Is there a link to the pre-trained model available? As well as any instructions for inference available?

**Comment by lucasxlu** [comment]
> Hey @lucasxlu ,
> 
> Thanks a lot for providing amazing results on the benchmark datasets. I was wondering on how to inference the TransFBP results on custom images. Is there a link to the pre-trained model available? As well as any instructions for inference available?

Please refer to [infer.py](https://github.com/lucasxlu/TransFBP/blob/master/main/infer.py) for inference. The pretrained model is shared via google drive, and link can be found from README. You may need to crop facial region with a face detector like MTCNN or dlib first.

**Comment by amil-rp-work** [comment]
Thanks will try out and let you know!
